[[build]]
base = "python:3.9"  # Replace with your Python version
commands = [
    "python -m venv /opt/venv",  # Create virtual environment
    ". /opt/venv/bin/activate", # Activate virtual environment
    "pip install -r requirements.txt" # Install dependencies
]

[[start]]
command = "python app.py"  # Adjust this if your main file has a different name
